version: '3.9'
services:
  db:
    image: postgres:16.0
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: lab-springboot3
    ports:
      - 5432:5432
    expose:
      - 5432
    networks:
      - lab-springboot3-network
  lab-springboot3:
    image: breno500as/lab-springboot3
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      SPRING.DATASOURCE.URL: jdbc:postgresql://db:5432/lab-springboot3
      SPRING.DATASOURCE.USERNAME: postgres
      SPRING.DATASOURCE.PASSWORD: root
    ports:
      - 80:80
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - lab-springboot3-network
networks:
  lab-springboot3-network:
    driver: bridge