version: '3.9'
services:
  db:
    image: postgres:16.0
    restart: always
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: lab-springboot3
    ports:
      - 5433:5433
    expose:
      - 5433
    networks:
      - lab-springboot3-network
  lab-springboot3:
    image: breno500as/lab-springboot3
    restart: always
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:postgresql://db:5433/lab-springboot3
      SPRING.DATASOURCE.USERNAME: postgres
      SPRING.DATASOURCE.PASSWORD: root
    ports:
      - 80:80
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - lab-springboot3-network
networks:
  lab-springboot3-network:
    driver: bridge