name: Java CI with Maven

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Set up JDK 20
      uses: actions/setup-java@v3
      with:
        java-version: '20'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn clean package
    - name: Docker Setup QEMU
      uses: docker/setup-qemu-action@v3.0.0
    - name: Docker Buildx Bake
      uses: docker/bake-action@v3.1.0
    - name: Docker build 
      run: docker-build -t ${{ secrets.DOCKER_USERNAME }}/lab-springboot3:latest -f docker/Dockerfile .
    - name: Push to Docker Hub
      run: |
       docker tag ${{ secrets.DOCKER_USERNAME }}/lab-springboot3:latest ${{ secrets.DOCKER_USERNAME }}/lab-springboot3:${{github.run_id}} 
       docker push  ${{ secrets.DOCKER_USERNAME }}/lab-springboot3:${{github.run_id}}
